---
- name: update cloudconfig
  hosts: coreos
  serial: 1
  gather_facts: no
  user: core

  roles:
    - role: kubectl
    - role: etcd-certificates
    - role: kubernetes-certificates
    - role: kubectl-config
    - role: extra-cas
    - ceph-on-kubernetes-config
    #- ceph-on-kubernetes-resources
    - role: cloud-config
    #- role: drain
    #- { role: unsafe_reboot, unsafe_reboot_dealay=900 }
    - role: safe_reboot
 
