---
- name: reboot server
  shell: sleep 5 && reboot &
  sudo: yes
  args:
      executable: /bin/bash
  async: 10
  poll: 0


- name: waiting for server to go down
  local_action: 
      module: wait_for
      host: "{{ inventory_hostname }}"
      port: 22
      delay: 1
      timeout: 60
      state: stopped

- name: waiting for server to come back
  local_action: 
    module: wait_for 
      host={{ inventory_hostname }} 
      port=22 
      delay=1 
      timeout=60
- name: wait some time to let the server rejoin the etcd cluster
  pause: seconds={{ unsafe_reboot_dealay|default("300") }}

